---
- name: Create manifests directory on first ctl_node
  file:
    path: /var/lib/rancher/{{ k8s_distribution }}/server/manifests
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Download vip rbac manifest to first ctl_node
  get_url:
    url: "https://kube-vip.io/manifests/rbac.yaml"
    dest: "/var/lib/rancher/{{ k8s_distribution }}/server/manifests/kube-vip-rbac.yaml"
    owner: root
    group: root
    mode: 0644

- name: Copy vip manifest to first ctl_node
  template:
    src: "vip.yaml.j2"
    dest: "/var/lib/rancher/{{ k8s_distribution }}/server/manifests/vip.yaml"
    owner: root
    group: root
    mode: 0644

- name: Download vip cloud provider manifest to first ctl_node
  get_url:
    url: "https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/{{ kube_vip_cloud_provider_tag_version | default('main') }}/manifest/kube-vip-cloud-controller.yaml"
    dest: "/var/lib/rancher/{{ k8s_distribution }}/server/manifests/kube-vip-cloud-controller.yaml"
    owner: root
    group: root
    mode: 0644