---
ansible_become_user: root
ansible_become_method: sudo
ansible_user: miked
ansible_become: true
ansible_ssh_private_key_file: ~/.ssh/mdemore-rsa
kube_vip_int: ens192
k8s_distribution: k3s
apiserver_endpoint: "192.168.1.170"
kube_vip_tag_version: "v0.8.0"